---
language: go
go:
  - "1.12.x"
env:
  - GO111MODULE=on
install:
  - go get golang.org/x/lint/golint
jobs:
  include:
    - stage: lint
      script: make lint
    - stage: test
      script: make test
    - stage: build
      script: make build
